#!/usr/bin/perl
/^\s*(\d+)\s+(\d+)\s*$/ and push @_,[$1,$2] and $_{$1}=$2 while <>;
open FILE, ">codewords.txt";
while (@_ > 1) {
    @_ = sort {$a->[1]<=>$b->[1]} @_;
    my @x = splice @_,0,2;
    push @_, [[map {$_->[0]} @x]];
    $_[-1][1]+=$_->[1] for @x;
}
sub x {
		if (ref $_[0]) { x($_[0][$_],$_[1].$_) for 0..$#{$_[0]}; }
		else { $b += (length $_[1]) * $_{$_[0]}; print FILE "$_[0]\t$_[1]\n"; }
}
if (ref $_[0][0]) {
    x $_[0][0];
} else {
    # Only a single character
    print FILE "$_[0][0]\t0\n";
}
print "$b\n";
